// Copyright © 2022-2023 IT ENGINEERING MANAGEMENT INC,
//                       <https://github.com/team113>
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU Affero General Public License v3.0 as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License v3.0 for
// more details.
//
// You should have received a copy of the GNU Affero General Public License v3.0
// along with this program. If not, see
// <https://www.gnu.org/licenses/agpl-3.0.html>.

import 'package:gherkin/gherkin.dart';
import 'package:messenger/domain/model/user.dart';
import 'package:messenger/provider/gql/graphql.dart';

import '../parameters/users.dart';
import '../world/custom_world.dart';

/// Sets the [UserLogin] of the provided [TestUser] to the generated value.
///
/// The value is generated by using `lgn_` prefix and [UserNum.val] and hence is
/// unique among all testing sessions.
final StepDefinitionGeneric setLogin = then1<TestUser, CustomWorld>(
  RegExp(r'{user} sets (?:his|her) login'),
  (TestUser user, context) async {
    final provider = GraphQlProvider();
    final CustomUser? customUser = context.world.sessions[user.name];
    provider.token = customUser?.token;
    final String newLogin = 'lgn_${customUser?.userNum.val}';
    await provider.updateUserLogin(UserLogin(newLogin));
    provider.disconnect();
  },
  configuration: StepDefinitionConfiguration()
    ..timeout = const Duration(minutes: 5),
);
