# Additional information about this file can be found here:
# https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    experimental_member_use: ignore
    invalid_use_of_visible_for_testing_member: error
  exclude:
    - '**/*.g.dart'
    - '**/*.graphql.dart'
    - '**/*.mocks.dart'
    - 'build/**.dart'

linter:
  # List of all available lints can be found here:
  # https://dart-lang.github.io/linter/lints/index.html
  rules:
    prefer_single_quotes: true
    prefer_relative_imports: true
