// Copyright © 2025-2026 Ideas Networks Solutions S.A.,
//                       <https://github.com/tapopa>
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU Affero General Public License v3.0 as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License v3.0 for
// more details.
//
// You should have received a copy of the GNU Affero General Public License v3.0
// along with this program. If not, see
// <https://www.gnu.org/licenses/agpl-3.0.html>.

import 'package:collection/collection.dart';

import '/util/new_type.dart';
import 'deposit.dart';

// ignore_for_file: constant_identifier_names

/// Country code in ISO 3166-1 alpha-2 format.
///
/// [ISO 3166-1 alpha-2]: https://www.iso.org/iso-3166-country-codes.html
class CountryCode extends NewType<String> {
  const CountryCode(super.val);
}

/// All known country codes in [ISO 3166-1 alpha-2] format.
///
/// [ISO 3166-1 alpha-2]: https://www.iso.org/iso-3166-country-codes.html
enum IsoCode {
  AC,
  AD,
  AE,
  AF,
  AG,
  AI,
  AL,
  AM,
  AO,
  AR,
  AS,
  AT,
  AU,
  AW,
  AX,
  AZ,
  BA,
  BB,
  BD,
  BE,
  BF,
  BG,
  BH,
  BI,
  BJ,
  BL,
  BM,
  BN,
  BO,
  BQ,
  BR,
  BS,
  BT,
  BW,
  BY,
  BZ,
  CA,
  CC,
  CD,
  CF,
  CG,
  CH,
  CI,
  CK,
  CL,
  CM,
  CN,
  CO,
  CR,
  CU,
  CV,
  CW,
  CX,
  CY,
  CZ,
  DE,
  DJ,
  DK,
  DM,
  DO,
  DZ,
  EC,
  EE,
  EG,
  EH,
  ER,
  ES,
  ET,
  FI,
  FJ,
  FK,
  FM,
  FO,
  FR,
  GA,
  GB,
  GD,
  GE,
  GF,
  GG,
  GH,
  GI,
  GL,
  GM,
  GN,
  GP,
  GQ,
  GR,
  GS,
  GT,
  GU,
  GW,
  GY,
  HK,
  HN,
  HR,
  HT,
  HU,
  IC,
  ID,
  IE,
  IL,
  IM,
  IN,
  IO,
  IQ,
  IR,
  IS,
  IT,
  JE,
  JM,
  JO,
  JP,
  KE,
  KG,
  KH,
  KI,
  KM,
  KN,
  KP,
  KR,
  KW,
  KY,
  KZ,
  LA,
  LB,
  LC,
  LI,
  LK,
  LR,
  LS,
  LT,
  LU,
  LV,
  LY,
  MA,
  MC,
  MD,
  ME,
  MF,
  MG,
  MH,
  MK,
  ML,
  MM,
  MN,
  MO,
  MP,
  MQ,
  MR,
  MS,
  MT,
  MU,
  MV,
  MW,
  MX,
  MY,
  MZ,
  NA,
  NC,
  NE,
  NF,
  NG,
  NI,
  NL,
  NO,
  NP,
  NR,
  NU,
  NZ,
  OM,
  PA,
  PE,
  PF,
  PG,
  PH,
  PK,
  PL,
  PM,
  PR,
  PS,
  PT,
  PW,
  PY,
  QA,
  RE,
  RO,
  RS,
  RU,
  RW,
  SA,
  SB,
  SC,
  SD,
  SE,
  SG,
  SH,
  SI,
  SJ,
  SK,
  SL,
  SM,
  SN,
  SO,
  SR,
  SS,
  ST,
  SV,
  SX,
  SY,
  SZ,
  TA,
  TC,
  TD,
  TG,
  TH,
  TJ,
  TK,
  TL,
  TM,
  TN,
  TO,
  TR,
  TT,
  TV,
  TW,
  TZ,
  UA,
  UG,
  US,
  UY,
  UZ,
  VA,
  VC,
  VE,
  VG,
  VI,
  VN,
  VU,
  WF,
  WS,
  XK,
  YE,
  YT,
  ZA,
  ZM,
  ZW;

  const IsoCode();

  /// Constructs an [IsoCode] from the provided [value].
  static IsoCode? fromJson(String value) {
    return values.firstWhereOrNull((e) => e.name == value);
  }

  /// Returns a [String] from this [IsoCode].
  String toJson() => name;
}

/// Extention adding ability to list restricted [IsoCode] for [DepositKind]s.
extension IsoCodeExtension on IsoCode {
  /// Returns [IsoCode]s that aren't available for the provided [DepositKind].
  static Set<IsoCode> restricted(DepositKind provider) {
    switch (provider) {
      case DepositKind.payPal:
        return IsoCode.values
            .whereNot((e) => available(provider).contains(e))
            .toSet();
    }
  }

  /// Returns [IsoCode] that are available for the provided [DepositKind].
  static Set<IsoCode> available(DepositKind provider) {
    switch (provider) {
      case DepositKind.payPal:
        return {
          IsoCode.DZ,
          IsoCode.AO,
          IsoCode.BJ,
          IsoCode.BW,
          IsoCode.BF,
          IsoCode.BI,
          IsoCode.ET,
          IsoCode.CI,
          IsoCode.CM,
          IsoCode.KE,
          IsoCode.MR,
          IsoCode.MU,
          IsoCode.CV,
          IsoCode.TD,
          IsoCode.KM,
          IsoCode.CD,
          IsoCode.DJ,
          IsoCode.EG,
          IsoCode.ER,
          IsoCode.GA,
          IsoCode.GM,
          IsoCode.GN,
          IsoCode.GW,
          IsoCode.LS,
          IsoCode.MG,
          IsoCode.MW,
          IsoCode.ML,
          IsoCode.YT,
          IsoCode.MA,
          IsoCode.MZ,
          IsoCode.NA,
          IsoCode.NE,
          IsoCode.NG,
          IsoCode.CG,
          IsoCode.RE,
          IsoCode.SH,
          IsoCode.ST,
          IsoCode.SN,
          IsoCode.SC,
          IsoCode.SL,
          IsoCode.SO,
          IsoCode.ZA,
          IsoCode.SZ,
          IsoCode.TZ,
          IsoCode.TG,
          IsoCode.TN,
          IsoCode.UG,
          IsoCode.ZM,
          IsoCode.ZW,
          IsoCode.AI,
          IsoCode.AG,
          IsoCode.AR,
          IsoCode.AW,
          IsoCode.BS,
          IsoCode.BB,
          IsoCode.BZ,
          IsoCode.BM,
          IsoCode.BO,
          IsoCode.BR,
          IsoCode.VG,
          IsoCode.CA,
          IsoCode.KY,
          IsoCode.CL,
          IsoCode.CO,
          IsoCode.CR,
          IsoCode.DM,
          IsoCode.DO,
          IsoCode.EC,
          IsoCode.SV,
          IsoCode.FK,
          IsoCode.GF,
          IsoCode.GL,
          IsoCode.GD,
          IsoCode.GP,
          IsoCode.GT,
          IsoCode.GY,
          IsoCode.HN,
          IsoCode.JM,
          IsoCode.MQ,
          IsoCode.MX,
          IsoCode.MS,
          IsoCode.NI,
          IsoCode.PA,
          IsoCode.PY,
          IsoCode.PE,
          IsoCode.KN,
          IsoCode.LC,
          IsoCode.PM,
          IsoCode.VC,
          IsoCode.SR,
          IsoCode.TT,
          IsoCode.TC,
          IsoCode.US,
          IsoCode.UY,
          IsoCode.VE,
          IsoCode.AM,
          IsoCode.AU,
          IsoCode.BH,
          IsoCode.BT,
          IsoCode.BN,
          IsoCode.KH,
          IsoCode.CN,
          IsoCode.CK,
          IsoCode.FJ,
          IsoCode.PF,
          IsoCode.IN,
          IsoCode.ID,
          IsoCode.IL,
          IsoCode.JP,
          IsoCode.JO,
          IsoCode.KZ,
          IsoCode.KI,
          IsoCode.KW,
          IsoCode.KG,
          IsoCode.LA,
          IsoCode.MY,
          IsoCode.MV,
          IsoCode.MH,
          IsoCode.FM,
          IsoCode.MN,
          IsoCode.NR,
          IsoCode.NP,
          IsoCode.NC,
          IsoCode.NZ,
          IsoCode.NU,
          IsoCode.NF,
          IsoCode.OM,
          IsoCode.PW,
          IsoCode.PG,
          IsoCode.PH,
          IsoCode.QA,
          IsoCode.WS,
          IsoCode.SA,
          IsoCode.SG,
          IsoCode.SB,
          IsoCode.KR,
          IsoCode.LK,
          IsoCode.TW,
          IsoCode.TJ,
          IsoCode.TH,
          IsoCode.TO,
          IsoCode.TM,
          IsoCode.TV,
          IsoCode.AE,
          IsoCode.VU,
          IsoCode.VN,
          IsoCode.WF,
          IsoCode.YE,
          IsoCode.AL,
          IsoCode.AD,
          IsoCode.AT,
          IsoCode.AZ,
          IsoCode.BE,
          IsoCode.BA,
          IsoCode.BG,
          IsoCode.HR,
          IsoCode.CY,
          IsoCode.CZ,
          IsoCode.DK,
          IsoCode.EE,
          IsoCode.FO,
          IsoCode.FI,
          IsoCode.FR,
          IsoCode.GE,
          IsoCode.DE,
          IsoCode.GR,
          IsoCode.HU,
          IsoCode.IS,
          IsoCode.IE,
          IsoCode.IT,
          IsoCode.LV,
          IsoCode.LI,
          IsoCode.LT,
          IsoCode.LU,
          IsoCode.MK,
          IsoCode.MT,
          IsoCode.MD,
          IsoCode.MC,
          IsoCode.ME,
          IsoCode.NL,
          IsoCode.NO,
          IsoCode.PL,
          IsoCode.PT,
          IsoCode.RO,
          IsoCode.SM,
          IsoCode.RS,
          IsoCode.SK,
          IsoCode.SI,
          IsoCode.ES,
          IsoCode.SJ,
          IsoCode.SE,
          IsoCode.CH,
          IsoCode.UA,
          IsoCode.GB,
          IsoCode.VA,
          IsoCode.RW,
          IsoCode.RU,
          IsoCode.BY,
        };
    }
  }
}
