// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZx-XVNlW1Gg4DGhCG_aXDWIVrIq3OqKU',
    appId: '1:311946098564:web:021f17b0fe4b89f192cfd1',
    messagingSenderId: '311946098564',
    projectId: 'gapopa-17fe9',
    authDomain: 'gapopa-17fe9.firebaseapp.com',
    storageBucket: 'gapopa-17fe9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAorXWOyLVpX22RjxXQGlJJTp6um6C1-3Y',
    appId: '1:311946098564:android:a0b14a54744bf0b092cfd1',
    messagingSenderId: '311946098564',
    projectId: 'gapopa-17fe9',
    storageBucket: 'gapopa-17fe9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDclPUBjoBbAm4d0vUil0JCzOYI6OTqcAM',
    appId: '1:311946098564:ios:cdf515f23f62c5aa92cfd1',
    messagingSenderId: '311946098564',
    projectId: 'gapopa-17fe9',
    storageBucket: 'gapopa-17fe9.appspot.com',
    iosClientId: '311946098564-7camofj5j86kdkbnsqni297b1ua7rov0.apps.googleusercontent.com',
    iosBundleId: 'com.team113.messenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDclPUBjoBbAm4d0vUil0JCzOYI6OTqcAM',
    appId: '1:311946098564:ios:cdf515f23f62c5aa92cfd1',
    messagingSenderId: '311946098564',
    projectId: 'gapopa-17fe9',
    storageBucket: 'gapopa-17fe9.appspot.com',
    iosClientId: '311946098564-7camofj5j86kdkbnsqni297b1ua7rov0.apps.googleusercontent.com',
    iosBundleId: 'com.team113.messenger',
  );
}
