# Copyright © 2022 IT ENGINEERING MANAGEMENT INC, <https://github.com/team113>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License v3.0 as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License v3.0 for
# more details.
#
# You should have received a copy of the GNU Affero General Public License v3.0
# along with this program. If not, see
# <https://www.gnu.org/licenses/agpl-3.0.html>.

image:
  repository: ghcr.io/team113/messenger
  tag: latest
  pullPolicy: IfNotPresent

# Remotely available application configuration.
# See `assets/conf.toml` for details.
conf: {}

# Additional labels to apply to all Kubernetes resources created by this chart.
labels: {}
  #app.kubernetes.io/part-of: messenger

deployment:
  replicas: 1
  revisionHistoryLimit: 0

  # Optional revision number to use for fine-grained Deployment rollouts.
  revision: ""

  annotations: {}
    #kubernetes.io/change-cause: kubectl set ...

  affinity: {}
    #nodeAffinity:
    #  requiredDuringSchedulingIgnoredDuringExecution:
    #    nodeSelectorTerms:
    #      - matchExpressions:
    #        - key: node-label-key
    #          operator: In
    #          values: ["node-label-value"]

  tolerations: []
    #- key: "node.alpha.kubernetes.io/unreachable"
    #  operator: "Exists"
    #  effect: "NoExecute"

  resources: {}
    #limits:
    #  cpu: 100m
    #  memory: 128Mi
    #requests:
    #  cpu: 100m
    #  memory: 128Mi

  # Container sources may be mounted to the specified host path.
  # This allows to develop the project without rebuilding container each time
  # or using SFTP.
  src:
    hostPath: ""

service:
  type: ClusterIP

ingress:
  enabled: yes

  # Hosts must be specified without "www." part.
  hosts:
    - messenger.test

  tls:
    enabled: no
    auto: no
    # Not required when "auto" is enabled.
    secretName:
      messenger.test: messenger.test.tls

  httpAuth:
    enabled: no

  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "30m"


sftp:
  enabled: no

  image:
    repository: atmoz/sftp
    tag: latest
    pullPolicy: IfNotPresent

  port: ""
  user: user
  pass: changeme

  resources: {}
    #limits:
    #  cpu: 50m
    #  memory: 5Mi
    #requests:
    #  cpu: 1m
    #  memory: 1Mi
