# Copyright © 2022-2026 IT ENGINEERING MANAGEMENT INC,
#                       <https://github.com/team113>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License v3.0 as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License v3.0 for
# more details.
#
# You should have received a copy of the GNU Affero General Public License v3.0
# along with this program. If not, see
# <https://www.gnu.org/licenses/agpl-3.0.html>.

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Publish a new internal build to TestFlight"
  lane :internal do
    setup_ci if ENV['CI']

    app_store_connect_api_key
    upload_to_testflight(ipa: "app.ipa")
  end

  desc "Publish a new version to App Store"
  lane :publish do
    setup_ci if ENV['CI']

    app_store_connect_api_key
    upload_to_app_store(
      force: true,
      ipa: "app.ipa",
      overwrite_screenshots: true,
      precheck_include_in_app_purchases: false,
      screenshot_processing_timeout: 120,
      submit_for_review: true
    )
  end

  desc "Validate the binary and its metadata against App Store rules"
  lane :validate do
    setup_ci if ENV['CI']

    app_store_connect_api_key
    upload_to_app_store(
      ipa: "app.ipa",
      overwrite_screenshots: true,
      precheck_include_in_app_purchases: false,
      screenshot_processing_timeout: 120,
      verify_only: true
    )
  end
end
