# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV['CI']
    api_key = app_store_connect_api_key(key_id: ENV['APP_STORE_CONNECT_API_KEY_KEY_ID'],
                                        issuer_id: ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID'],
                                        key_filepath: ENV['APP_STORE_CONNECT_API_KEY_KEY_FILEPATH'])
    upload_to_testflight(ipa: "app.ipa",
                         api_key: api_key)
  end
end
